# Generated by Django 2.1.6 on 2019-05-15 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
